analyzer:
  exclude:
    - packages/flutter_pty/**
    - packages/xterm/**

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    require_trailing_commas: true